A vote was received but failed processing. The error message is 
contained in the subject line of this message. Please reread the
section on voting procedures in the Call For Votes (CFV) and
vote again.

For information about ausadmin and voting procedures, and
for details on votes currently running, upcoming and
completed, please visit http://aus.news-admin.org/

If you have a problem please contact the aus Newsgroup 
Administrator Nick Andrew <ausadmin@aus.news-admin.org>. 
