
This is an automatic message sent to you after your vote has been counted.
If this is correct, there is no need for you to reply. 

This is a public vote, and all addresses and votes will be listed in the 
final voting results.

For a copy of the Call For Votes (CFV) email cfv@aus.news-admin.org 
indicating the newsgroup in the subject line.

If you have a problem please contact the aus Newsgroup 
Administrator Nick Andrew <ausadmin@aus.news-admin.org>. 
