
This is an automatic message sent to you after your vote has been counted.
If this is correct, there is no need for you to reply. 

This is a public vote, and all addresses and votes will be listed in the 
final voting results.

For information about ausadmin and voting procedures, and
for details on votes currently running, upcoming and
completed, please visit http://aus.news-admin.org/

If you have a problem please contact the aus Newsgroup 
Administrator Nick Andrew <ausadmin@aus.news-admin.org>. 
