A vote was received but failed processing. The error message is 
contained in the subject line of this message. Please reread the
section on voting procedures in the Call For Votes (CFV) and
vote again if appropriate.

The vote-processing program can return the following errors
listed below, with explanations.


Message: "Invalid newsgroup name"

   You've tried to vote on something which just doesn't look like a
   newsgroup name to our program. A newsgroup name looks something
   like "aus.whatever" or "aus.sport.roller-skates" but definitely not
   "aus.whatever." or "AUS.WHATEVER".


Message: "Invalid newsgroup <newsgroup>"

   That newsgroup isn't one that is being handled by ausadmin. Either
   it's not an aus group, or it already exists, or it's otherwise not
   being voted on.


Message: "A vote for <newsgroup> has not (yet) started"

   That newsgroup is probably still in the RFD stage (Request For
   Discussion) and voting on it hasn't opened yet.


Message: "The vote for <newsgroup> has been cancelled"

   For some reason or another a vote was started and then was cancelled
   without completion. Go to http://aus.news-admin.org/ and click on
   the newsgroup name for more detail.


Message: "<newsgroup> vote ended"

   You're too late to vote.


Message: "invalid newsgroup <newsgroup>"

   Some other error happened which means the program can't accept your vote.


Message: "already voted on <newsgroup>"

   Your email address already has a vote recorded for this newsgroup.

If you still have a problem please e-mail <ausadmin@aus.news-admin.org>.
